export default {
  '/unitInfoManagement': '单位信息管理',
  '/deptMg': '部门信息管理',
  '/postMg': '岗位信息管理',
  '/userGroupMg': '用户组信息管理',
  '/userInfoManagement': '用户信息管理',
  '/sysRole': '系统角色',
  '/allRole': '全局角色',
  '/unitRole': '单位角色',
  '/test': '单位角色111',
  '/formEngine': '表单引擎',
  '/workflowEngine': '流程引擎',
  '/businessUseSort': '业务应用类别',
  '/dataRuleMg': '数据规则定义',
  '/moduleResourceMg': '模块资源管理',
  '/buttonLibrary': '按钮库',
  '/buttonSolution': '按钮方案',
  '/systemLayout': '系统配置',
  '/tenantSettings': '租户配置',
  '/userInfoManagement/userView': '管理',
  '/basicDataForm': '基础数据码表',
  '/applyModel': '业务应用建模',
  '/applyModelConfig': '业务应用配置',
  '/applyModelFormAuth': '权限',
  '/listMoudles': '列表建模',
  '/pluginManage': '插件管理',
  '/pluginManageNoButton': '插件管理查看',
  '/listMoudles/moudleDesign': '列表设计',
  '/dataDriven': '数据驱动',
  '/eventRegister': '事件注册器',
  '/passwordMg': '密码管理',
  '/platformCodeRules': '平台编码规则',
  '/writeSignStyle': '手写签批样式管理',
  '/businessUseSort': '业务应用类别',
  '/businessFormManage': '业务表单管理',
  '/useDataBuildModel': '应用数据建模',
  '/holidaysManage': '节假日维护',
  '/useDataBuildModel': '应用数据建模',
  '/entranceConfig': '入口配置',
  '/iconConfig': '图标配置',
  '/viewOrgPic': '查看结构图',
  '/globalReviewer': '全局审核人',
  '/accreditLook': '授权查看',
  '/workRule': '事项规则',
  '/controlManagement':'业务控件管理',
  '/systemAccess':'系统接入',
  '/openSystem':'开放系统',
  '/templateEditor': '打印设置',
  '/applyCorrelation':'业务应用关联',
  '/demo':'demo',
  '/interfaceManagement':'接口管理',
  '/desktopLayout': '桌面布局',
  '/sceneConfig': '场景配置',
  '/incompatibleFunctionClassify':'职能分类',
  '/incompatibleRoleAlert': '角色预警',
  '/incompatibleSettings': '不相容设置',
  '/applyPublish':'应用发布',
  '/yangzhe':'查看指标日志',
  '/funManage':'函数管理',
};
