module.exports = {
    BASE_WIDTH: (150 / 1660) * window.screen.width, // 基础宽度
    ORDER_WIDTH: 60, // 序号宽度
    PADDING_HEIGHT: 20, // padding 高度
    TABLE_HEAD_HEIGHT: 40, // 表格头高度
    PAGE_NATION_HEIGHT: 48, // 分页表格高度
    REQUEST_SUCCESS: 200,
    defaultLayoutState: {
        settings: {
            hasHeaders: true,
            constrainDragToContainer: false,
            reorderEnabled: true,
            selectionEnabled: false,
            popoutWholeStack: false,
            blockedPopoutsThrowError: true,
            closePopoutsOnUnload: true,
            showPopoutIcon: false,
            showMaximiseIcon: false,
            showCloseIcon: true,
            responsiveMode: 'onload',
            tabOverlapAllowance: 0,
            reorderOnTabMenuClick: true,
            tabControlOffset: 10,
        },
        dimensions: {
            borderWidth: 15,
            borderGrabWidth: 15,
            minItemHeight: 10,
            minItemWidth: 10,
            headerHeight: 20,
            dragProxyWidth: 500,
            dragProxyHeight: 300,
        },
        labels: {
            close: '关闭',
            maximise: '最大化',
            minimise: '最小化',
            popout: '弹出',
            popin: 'pop in',
            tabDropdown: 'additional tabs',
        },
        content: [
            {
                type: 'row',
                isClosable: true,
                reorderEnabled: true,
                title: '',
                height: 100,
                content: [
                    {
                        type: 'stack',
                        header: {},
                        isClosable: true,
                        reorderEnabled: true,
                        title: '',
                        activeItemIndex: 0,
                        width: 58.769230769230774,
                        height: 100,
                        content: [
                            {
                                title: '工作事项',
                                type: 'component',
                                component: 'ColumnWorkList',
                                componentName: 'lm-react-component',
                                isClosable: true,
                                reorderEnabled: true,
                            },
                        ],
                    },
                    {
                        type: 'column',
                        isClosable: true,
                        reorderEnabled: true,
                        title: '',
                        width: 41.230769230769226,
                        content: [
                            {
                                type: 'stack',
                                header: {},
                                isClosable: true,
                                reorderEnabled: true,
                                title: '',
                                activeItemIndex: 0,
                                height: 50,
                                content: [
                                    {
                                        title: '日程管理',
                                        type: 'component',
                                        component: 'ColumnCalendar',
                                        componentName: 'lm-react-component',
                                        isClosable: true,
                                        reorderEnabled: true,
                                    },
                                ],
                            },
                            {
                                type: 'stack',
                                header: {},
                                isClosable: true,
                                reorderEnabled: true,
                                title: '',
                                activeItemIndex: 0,
                                height: 50,
                                width: 41.230769230769226,
                                content: [
                                    {
                                        title: '通知公告',
                                        type: 'component',
                                        component: 'ColumnNotice',
                                        componentName: 'lm-react-component',
                                        isClosable: true,
                                        reorderEnabled: true,
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
        isClosable: true,
        reorderEnabled: true,
        title: '',
        openPopouts: [],
        maximisedItemId: null,
    },
    emptyLayoutState: {
        settings: {
            hasHeaders: true,
            constrainDragToContainer: false,
            reorderEnabled: true,
            selectionEnabled: false,
            popoutWholeStack: false,
            blockedPopoutsThrowError: true,
            closePopoutsOnUnload: true,
            showPopoutIcon: false,
            showMaximiseIcon: false,
            showCloseIcon: true,
            responsiveMode: 'onload',
            tabOverlapAllowance: 0,
            reorderOnTabMenuClick: true,
            tabControlOffset: 10,
        },
        dimensions: {
            borderWidth: 15,
            borderGrabWidth: 15,
            minItemHeight: 10,
            minItemWidth: 10,
            headerHeight: 20,
            dragProxyWidth: 500,
            dragProxyHeight: 300,
        },
        labels: {
            close: '关闭',
            maximise: '最大化',
            minimise: '最小化',
            popout: '弹出',
            popin: 'pop in',
            tabDropdown: 'additional tabs',
        },
        content: [],
        isClosable: true,
        reorderEnabled: true,
        title: '',
        openPopouts: [],
        maximisedItemId: null,
    },

    NORM_STATE: {
        '': '未结转',
        0: '已收回',
        1: '未结转',
        2: '已结转',
        3: '未结转',
    },
    LH_STATE: {
        '': '未结转',
        0: '未结转',
        1: '已结转',
    },
    YES_NO: {
        0: '否',
        1: '是',
    },
    BUDGET_TYPE: {
        0: '禁用',
        1: '提醒',
        3: '不管控',
    },
    BIZSTATUS: {
        //已办事项状态
        0: '待发',
        1: '在办',
        2: '办结',
    },
    EXECSTATE: {
        //已办事项状态
        0: '报销未完成',
        1: '报销已完成',
        2: '撤销',
    },
    HISTORYTYPE: {
        3: '执行记录',
        4: '在途执行记录',
    },
};
